- opengemini-client-api/src/main/java/io/opengemini/client/api/OpenGeminiException.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/Configuration.java
- pom.xml
> feat: add tls config in jdk client

- opengemini-client-api/src/main/java/io/opengemini/client/api/Address.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/AuthConfig.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/AuthType.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/BatchConfig.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/OpenGeminiClient.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/Query.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/QueryResult.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/Configuration.java
> feat: add config to client

- opengemini-client-api/src/main/java/io/opengemini/client/api/AuthConfig.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/BaseConfiguration.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/InsecureTrustManager.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/OpenGeminiClient.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/OpengeminiConst.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/SslContextUtil.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/TlsConfig.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/OpenGeminiJdkClient.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/OpenGeminiJdkClientFactory.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/api/OpenGeminiJdkClientFactoryTest.java
initialize the OpenGeminiJdkClient class
> feat: initialize the OpenGeminiJdkClient class

- opengemini-client-api/src/main/java/io/opengemini/client/api/Address.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/BaseConfiguration.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/Query.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/Series.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/SeriesResult.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/TlsConfig.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/OpenGeminiJdkClient.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/common/OpenGeminiCommon.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/common/package-info.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/jdk/OpenGeminiJdkClientFactoryTest.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/jdk/OpenGeminiJdkClientTest.java
- pom.xml
- add some field of QueryResult 
- add async query method of jdk http client, using round robin to get the server address
- add one test that can not connect
> feat: add query method of jdk http client

- opengemini-client-api/src/main/java/io/opengemini/client/api/Query.java
chore: remove extra semicolons
> chore: remove extra semicolons

- opengemini-client-api/src/main/java/io/opengemini/client/api/Point.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/jdk/OpenGeminiJdkClientTest.java
> fix: points with additional fields writing error

- opengemini-client-common/src/main/java/io/opengemini/client/common/InsecureTrustManager.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/SslContextUtil.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OkHttpSslContextFactory.java
> refactor: move InsecureTrustManager from api module to common module

- ci/checkstyle/checkstyle.xml
- opengemini-client-api/src/main/java/io/opengemini/client/api/Query.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/InsecureTrustManager.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/SslContextUtil.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OkHttpSslContextFactory.java
- opengemini-client-reactor/src/main/java/io/opengemini/client/reactor/SslContextUtil.java
- pom.xml
> build: add spotless-maven-plugin and checkstyle module

- .gitignore
- .idea/icon.svg
> chore: add icon in project (#66)

- opengemini-client-api/src/main/java/io/opengemini/client/api/TlsConfig.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/OpenGeminiJdkClient.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OkHttpSslContextFactory.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClient.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClientFactory.java
- opengemini-client-okhttp/src/test/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClientFactoryTest.java
- opengemini-client-reactor/src/main/java/io/opengemini/client/reactor/OpenGeminiReactorClient.java
> refactor: remove field's tls prefix in TlsConfig

- opengemini-client-api/pom.xml
- opengemini-client-asynchttpclient/src/main/java/io/opengemini/client/asynchttpclient/OpenGeminiAsyncHttpClient.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/OpenGeminiJdkClient.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/OpenGeminiJdkClientFactory.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClient.java
- opengemini-client-okhttp/src/main/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClientFactory.java
- opengemini-client-reactor/src/main/java/io/opengemini/client/reactor/OpenGeminiReactorClient.java
- opengemini-client-reactor/src/main/java/io/opengemini/client/reactor/OpenGeminiReactorClientFactory.java
- pom.xml
It's meaningless to create client with null configuration. I recommend add @NotNull annotation to hint user.
> feat: add NotNull annotation when create client

- opengemini-client-common/src/main/java/io/opengemini/client/common/SslUtil.java
- opengemini-client-jdk/src/main/java/io/opengemini/client/jdk/SslContextUtil.java
- opengemini-client-reactor/src/main/java/io/opengemini/client/reactor/SslContextUtil.java
> fix: eliminate the repetitive code for constructing ssl context. (#88)

- opengemini-client-asynchttpclient/src/test/java/io/opengemini/client/asynchttpclient/OpenGeminiAsyncHttpClientTest.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseAsyncClient.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/jdk/OpenGeminiJdkClientTest.java
- opengemini-client-okhttp/src/test/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClientTest.java
> feat: return directly when write empty point list

- opengemini-client-api/src/main/java/io/opengemini/client/api/Precision.java
- opengemini-client-api/src/main/java/io/opengemini/client/api/Query.java
- opengemini-client-asynchttpclient/src/test/java/io/opengemini/client/asynchttpclient/OpenGeminiAsyncHttpClientTest.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseClient.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/jdk/OpenGeminiJdkClientTest.java
- opengemini-client-okhttp/src/test/java/io/opengemini/client/okhttp/OpenGeminiOkhttpClientTest.java
> fix: add precision in query method

- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseAsyncClient.java
- opengemini-client-jdk/src/test/java/io/opengemini/client/jdk/OpenGeminiJdkClientTest.java
> fix: ignore point with no valid field

- opengemini-client-api/src/main/java/io/opengemini/client/api/Endpoint.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseClient.java
Part of #108 
Add endpoint struct, it can store server's status
> feat: add endpoint struct

- opengemini-client-asynchttpclient/src/main/java/io/opengemini/client/asynchttpclient/OpenGeminiAsyncHttpClient.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseClient.java
> feat: add health check scheduler

- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseClient.java
#108 
use HttpURLConnection instead HttpClient
> fix: add health check

- opengemini-client-api/src/main/java/io/opengemini/client/api/OpenGeminiAsyncClient.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseAsyncClient.java
- opengemini-client-common/src/main/java/io/opengemini/client/common/BaseClient.java
- opengemini-client/src/main/java/io/opengemini/client/impl/OpenGeminiClient.java
- opengemini-client/src/test/java/io/opengemini/client/impl/OpenGeminiClientTest.java
> fix: support write with rp (#113)

- spring/opengemini-spring-boot-starter-reactive/src/main/java/io/opengemini/client/spring/data/config/OpenGeminiReactiveAutoConfiguration.java
- spring/opengemini-spring-boot-starter/src/main/java/io/opengemini/client/spring/data/config/OpenGeminiAutoConfiguration.java
- spring/opengemini-spring/src/main/java/io/opengemini/client/spring/data/core/MeasurementOperations.java
> chore: set conditional on missing bean by class

- .github/workflows/pr-title-lint.yml
Add PR title lint CI to check if the submitted PR title does not meet the requirements.
> ci: add pr title lint

- .typos.toml
- opengemini-client/pom.xml
- pom.xml
Added gRPC as a dependency to the project.
Implemented code generation for gRPC services.
Defined the writeByGrpc interface for data handling.
> feat: Introduce gRPC support and code generation and define writeByGrpc interface
